name: retry-types
version: 0.1.0.0
github: "mbg/retry-types"
license: MIT
author: "Michael B. Gale"
maintainer: "github@michael-gale.co.uk"
copyright: "2022 Michael B. Gale"

extra-source-files:
  - README.md
  - ChangeLog.md

synopsis: Type-level representations of retry policies.
category: Data

description: Please see the README on GitHub at <https://github.com/mbg/retry-types#readme>

dependencies:
  - base >= 4.7 && < 5
  - retry

default-extensions:
  - DataKinds
  - FlexibleInstances
  - FunctionalDependencies
  - ImportQualifiedPost
  - KindSignatures
  - MultiParamTypeClasses
  - PolyKinds
  - ScopedTypeVariables
  - StandaloneKindSignatures
  - TypeApplications
  - TypeFamilies
  - TypeOperators

ghc-options:
  - -Wall

library:
  source-dirs: src

tests:
  retry-types-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - retry-types
      - tasty
      - tasty-hunit
      - tasty-hedgehog
      - hedgehog
